services:
  redis-server:
    container_name: redis-server
    build:
      context: .
      target: final
    ports:
      - 8080:80

    develop:
      watch:
        - action: rebuild
          path: .

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379 
